name: isca_env_tf
channels:
- conda-forge
dependencies:
- dask
- f90nml
- fortran-compiler
- ipykernel
- jinja2
- libgfortran
- netcdf-fortran
- numpy
- openmpi=4.*
- pandas
- python
- pip
- pytest
- sh
- tqdm
- xarray
- tensorflow
- keras
- netcdf4
